name: 'Needs Result Lookup'
description: 'Map needs.id.result to some value'
author: 'cwqt'
inputs:
  result:
    description: 'Result of need e.g. needs.id.result'
    required: true
  if-success:
    description: 'Output if result is "success"'
    default: ''
    required: false
  if-failure:
    description: 'Output if result is "failure"'
    default: ''
    required: false
  if-cancelled:
    description: 'Output if result is "cancalled"'
    default: ''
    required: false
  if-skipped:
    description: 'Output if result is "skipped"'
    default: ''
    required: false

outputs:
  value:
    description: 'Output value'

runs:
  using: 'node12'
  main: 'dist/index.js'

# Ref: https://haya14busa.github.io/github-action-brandings/
branding:
  icon: 'list'
  color: 'white'
